mysite/blog/urls.py
from django.conf.urls import url
from mysite.blog import views

urlpatterns = [
    url(r'^$',views.PostListView.as_view(),name='post_list'),
    url(r'^about/$',views.AboutView.as_view(),name='about'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('mysite.blog.urls')),
    url(r'accounts/logout/$',views.logout,name='logout',kwargs={'next_page':'/'}),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("post_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.text

mysite/blog/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post,Comment

class PostForm(forms.ModelForm):
    text = forms.CharField(widget=PagedownWidget(show_preview=False))
    published_date = forms.DateField(widget=forms.SelectDateWidget, required=False)
    class Meta:
        model = Post
        fields = ('author','title', 'text', 'published_date')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author','text')

        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from mysite.blog.models import Post, Comment
from django.utils import timezone
from mysite.blog.forms import PostForm, CommentForm

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

class AboutView(TemplateView):
    template_name = "blog/about.html"

class PostListView(ListView):
    model = Post
    paginate_by = 4
    template_name = "blog/post_list.html"

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm

    model = Post


class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm

    model = Post


class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'

    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')

#######################################

#######################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)

mysite/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block header %}{% endblock header %}

{% block content %}
 <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-14 mx-auto">
       <div class="page-heading">
         <h1>About Thomas</h1>
         <span class="subheading">Clichees & Sterotypes</span>
       </div>
      </div>
    </div>
 </div>
</header>

<!-- Main Content -->
<div class="container">
 <div class="row">
    <div class="col-lg-12 col-md-14 mx-auto">
        <p>Your probably wondering where the hell you are right now in the jungle that is the World Wide Web! No need to be afraid am not currently stealing your cookies and cleaning out your bank account :)</p>
        <p>My name is Thomas and I am currently trying my hardest to learn programming and web development…. It’s not easy, but its fun!</p>
        <p>I am and have been for the past 8 years working in the service industry or to put it more  accurately in the trenches of Normandy. It’s challenging work at times, dealing with volumes of people is never easy but I have gained much experience in the subtle art of the human interaction.</p>
        <p>I started my programming journey in order to solve problems and make my work as a manager easier (I am kind of lazy….but in a good way). Little did I know I would actually start to enjoy it so much, programming can become quite additive just ask my wife. So much so that I am now currently studying computer science at DIT.</p>
        <p>Since entering the world of web development I have had the pleasure to meet some of the most amazing individuals who have taken the time to sit down and help me along way. So I decided that its about time that I paid that forward and so this blog was born. </p>
        <p>I hope that you might find some worth in the articles I publish and that any of you aspiring to become programmers or hobbyists don’t make the same mistakes I did. </p>
        <p>Dedicated to Denis & Fabio for all the help as well as future help in Python & Django ;)</p>
    </div>
 </div>
</div>

{% endblock %}

mysite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>def learn( ):</title>

    <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
    <!-- Custom style sheet -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    {% block head_extra %}{% endblock head_extra %}

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'post_list' %}">def learn( ):</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post_list' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about'%}">About</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'post_new' %}" >New Post</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'post_draft_list' %}">Drafts</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'logout' %}" >Log out</a>
            </li>
            <li class="nav-item">
              <a >Hello : {{ user.username }}</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Header -->

    {% block header %}
    <header class="masthead" style="background-image: url({% static 'img/post-bg.jpg' %})">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h2 class="quote">Intellectual growth should commence at birth and cease only at death.</h2>
              <span class="subheading"><cite> - Albert Einstein</cite></span>
            </div>
          </div>
        </div>
      </div>
    </header>
     {% endblock header %}


    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
               {% block content %}
               {% endblock %}

    </div>


    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="https://www.linkedin.com/in/thomas-mcdonnell-350017149/">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://www.facebook.com/Thomas McDonnell">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/ThomasMcDonnell">
                  <span class="fa-stack fa-lg">
                    <i class="fa fa-circle fa-stack-2x"></i>
                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; def learn( ): 2017</p>
          </div>
        </div>
      </div>
    </footer>

    <script   src="https://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="   crossorigin="anonymous"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

    <script type="text/javascript">
    $(document).ready(function(){
         $(".content-markdown").each(function(){
              var content = $(this).text()
              var markedContent = marked(content.trim())
              $(this).html(markedContent)
         })
         $(".content-markdown img").each(function(){
              $(this).addClass("img-responsive");
         })

    })
    </script>
    <script>
    $(document).ready(function(){
         $("#comment").click(function(){
              $("#fade").fadeToggle();
         });
    });
    </script>
    <script>
    $(document).ready(function(){
         // preview-title
        var titleInput = $("#id_title");

        function setTitle(value){
             $("#preview-title").text(value)
        }
        setTitle(titleInput.val())

        titleInput.keyup(function(){
             var newContent = $(this).val()
             setTitle(newContent)
        })
        // preview-content
        var contentInput = $("#id_text");

        function setContent(value){
             var markedContent = marked(value)
             $("#preview-content").html(markedContent)
             $("#preview-content img").each(function(){
                  $(this).addClass("img-responsive")
             })
        }
        setContent(contentInput.val())

        contentInput.keyup(function(){
             var newContent = $(this).val()
             setContent(newContent)
        })
    });
    </script>
  </body>

</html>

mysite/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}

{% block header %}{% endblock header %}

{% block content %}
<h1>Comment</h1>
<form class="post-form" method="POST">
     {% csrf_token %}
     {{form.as_p}}
     <button type="submit" class='save ntn btn-default'>Post Comment</button>
</form>

<script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block header %}{% endblock header %}

{% block content %}
<div>
     <div class="alert alert-danger" role="alert">
          <form action="" method="post">{% csrf_token %}
               <p>Are you sure you want to delete "{{ object }}"?</p>
               <input class='btn btn-danger' type="submit" value="Yes" />
          </form>
     </div>
</div>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block header %}{% endblock header %}

{% block content %}

<header>
     <div class="container">
        <div class="row">
           <div class="col-lg-12 col-md-14 mx-auto">
             <div class="post-heading"><h1>{{ post.title }}</h1></div>
                  {% if post.published_date %}
                 <div class="date postdate">
                     <small>{{ post.published_date }}</small>
                 </div>

               {% else %}
                 <a class="btn btn-primary" href="{% url 'post_publish' pk=post.pk %}">Publish</a>
             {% endif %}
           </div>
        </div>
     </div>
</header>


        <article>
          <div class="container">
               <div class="row">
                    <div class="col-lg-12 col-md-14 mx-auto content-markdown">
                         {{ post.text }}
                    </div>
               </div>
          </div>
        </article>


      {% if user.is_authenticated %}
          <a class="btn btn-primary" href="{% url 'post_edit' pk=post.pk %}">Edit</a>
          <a class="btn btn-primary" href="{% url 'post_remove' pk=post.pk %}">Remove</a>
      {% endif %}



  <hr>
  <a class="btn btn-primary" href="{% url 'add_comment_to_post' pk=post.pk %}">Comment</a>
  <a class="btn btn-primary" id="comment">View Comments</a>
<div id="fade" style="display:none;">

  {% for comment in post.comments.all %}
  <br>
      {% if user.is_authenticated or comment.approved_comment %}
      <div>
           <blockquote>
                    <small>{{ comment.created_date }}</small>
                   {% if not comment.approved_comment %}
                       <a class="btn btn-secondary" href="{% url 'comment_remove' pk=comment.pk %}">remove</a>
                       <a class="btn btn-secondary" href="{% url 'comment_approve' pk=comment.pk %}">Ok</a>
                   {% endif %}

                    <p>{{ comment.text|safe|linebreaks }}</p>
                    <p>Posted by: <strong>{{ comment.author }}</strong></p>
            </blockquote>
      </div>

      {% endif %}
  {% empty %}
      <small id="fade" style="display:none;"><p>No comments posted.</p></small>
  {% endfor %}
</div>

{% endblock %}

mysite/blog/templates/blog/post_draft.html
{% extends 'blog/base.html' %}

{% block header %}{% endblock header %}

{% block content %}
    {% for post in posts %}
       <div>
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p class="content-markdown">{{ post.text|truncatechars:200 }}</p>
       </div>
    {% endfor %}
{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_filters %}

{% block header %}{% endblock header %}

{% block head_extra %}

{{ form.media }}

{% endblock head_extra %}



{% block content %}
<div id="block-preview" class="col-sm-6">
     <h1>Preview</h1>
     <div class="content-preview">
          <h3 id="preview-title"></h3>
          <p id="preview-content"></p>
     </div>
</div>


<div id="block-content" class="col-sm-6">
    <h1>New Post</h1>

    <form method="POST" class="post-form">
         {% csrf_token %}
         {{form|crispy}}
         <button type="submit" class="save btn btn-default">Save</button>
    </form>
</div>
{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}


{% block content %}

     {% for post in post_list %}
 <a href={% url 'post_detail' pk=post.pk %}>
   <h1>
        {{ post.title }}
   </h1>
 </a>
 <div class="date postdate"><small>{{ post.published_date }}</small></div>

<p class="post-meta content-markdown">
      {{ post.text|truncatechars:100 }}
</p>

   <p><small>Comments : {{ post.approve_comments.count }}</small></p>
   <hr>


{% endfor%}

  {% if is_paginated %}
    <nav>
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li>
            <a href="?page={{ page_obj.previous_page_number }}">
              <span>Previous</span>
            </a>
          </li>
        {% else %}
          <li class="disabled">
            <a href="#">
              <span>Previous</span>
            </a>
          </li>
        {% endif %}

        {% for page in paginator.page_range %}
          <li {% if page == page_obj.number %}class="active"{% endif %}>
            <a href="?page={{ page }}">{{ page }}</a>
          </li>
        {% endfor %}

        {% if page_obj.has_next %}
          <li>
            <a href="?page={{ page_obj.next_page_number }}">
              <span>Next</span>
            </a>
          </li>
        {% else %}
          <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
            <a href="#">
              <span>Next</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}

{% endblock %}